backend:
  name: github
<<<<<<< HEAD
  repo: Huxpro/huxpro.github.io # 替换为你的仓库名称，例如：你的用户名/你的仓库名
  branch: master # 替换为你的主分支名称，通常是 master 或 main
  base_url: https://github.com # 如果你的仓库在 GitHub Enterprise 上，需要修改
  auth_scope: repo # 确保有足够的权限
  app_id: YOUR_GITHUB_OAUTH_APP_ID # 稍后替换为你的 GitHub OAuth App ID

media_folder: "img/uploads" # 媒体文件将上传到这个文件夹
public_folder: "/img/uploads" # 媒体文件在网站上的公共路径

collections:
  - name: "blog" # 集合的名称
    label: "Blog Posts" # 在 CMS 界面中显示的名称
    folder: "_posts" # 你的博客文章所在的文件夹
    create: true # 允许在 CMS 中创建新文章
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 文章文件名的格式
    fields: # 定义文章的字段
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "Hux"} # 替换为你的作者名
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Category", name: "category", widget: "string", required: false}
      - {label: "Featured Image", name: "header-img", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
=======
  repo: Jieice/JieDimension # 使用您指定的GitHub仓库
  branch: gh-pages # GitHub Pages默认分支

media_folder: "images" # 媒体文件将存储在仓库的images文件夹中
public_folder: "/images" # 媒体文件的公共URL

# 启用编辑预览
show_preview_links: true

collections:
  - name: "posts" # 用于在路由中标识集合
    label: "博客文章" # 在UI中显示的名称
    folder: "_posts/design" # 存储文件的文件夹路径
    create: true # 允许用户创建新文件
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 文件名模板
    fields: # 要编辑的字段
      - {label: "布局", name: "layout", widget: "hidden", default: "page"}
      - {label: "副标题", name: "subheadline", widget: "string"}
      - {label: "标题", name: "title", widget: "string"}
      - {label: "摘要", name: "teaser", widget: "text"}
      - {label: "分类", name: "categories", widget: "list"}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "显示头部", name: "header", widget: "select", options: ["yes", "no"], default: "no"}
      - {label: "图片", name: "image", widget: "object", fields: [
          {label: "标题图片", name: "title", widget: "image", required: false},
          {label: "缩略图", name: "thumb", widget: "image", required: false},
          {label: "首页图片", name: "homepage", widget: "image", required: false},
          {label: "图片说明", name: "caption", widget: "string", required: false},
          {label: "说明链接", name: "caption_url", widget: "string", required: false}
        ]}
      - {label: "内容", name: "body", widget: "markdown"}
      
  - name: "pages" # 用于在路由中标识集合
    label: "页面" # 在UI中显示的名称
    folder: "pages" # 存储文件的文件夹路径
    create: true # 允许用户创建新文件
    fields: # 要编辑的字段
      - {label: "布局", name: "layout", widget: "select", options: ["page", "page-fullwidth"], default: "page"}
      - {label: "标题", name: "title", widget: "string"}
      - {label: "摘要", name: "teaser", widget: "text", required: false}
      - {label: "永久链接", name: "permalink", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}
>>>>>>> 01b5b3ba47b23071dd683b0700d15e8413e0da9c
